"""empty message

Revision ID: 09f65e48471a
Revises: fd30fc217bea
Create Date: 2022-02-03 14:32:07.137997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f65e48471a'
down_revision = 'fd30fc217bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'product', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_cart_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'cart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_cart_id_fkey', 'product', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'item_id')
    # ### end Alembic commands ###
