"""empty message

Revision ID: 5b24b8f1a709
Revises: af0605e48762
Create Date: 2022-01-30 18:29:54.180390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b24b8f1a709'
down_revision = 'af0605e48762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.add_column('inventory', sa.Column('name', sa.String(), nullable=False))
    op.add_column('inventory', sa.Column('value', sa.Integer(), nullable=False))
    op.add_column('inventory', sa.Column('item_type', sa.String(), nullable=False))
    op.add_column('inventory', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inventory', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'user_id')
    op.drop_column('inventory', 'item_type')
    op.drop_column('inventory', 'value')
    op.drop_column('inventory', 'name')
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    # ### end Alembic commands ###
