"""empty message

Revision ID: 7d4e4e354ead
Revises: cbfc9d6269d7
Create Date: 2022-02-03 16:02:04.284446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4e4e354ead'
down_revision = 'cbfc9d6269d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_username_key', 'post', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('post_username_key', 'post', ['username'])
    # ### end Alembic commands ###
